name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.org'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.org'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - snapshot
    steps:
    - uses: actions/checkout@v3
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master

    - name: Run tests
      run: |
        make test
